return {
    ["riotball600"] = {
      usedefaultexplosions = false,
      groundflash = {
        alwaysvisible      = false,
        circlealpha        = 0.2,
        circlegrowth       = 13.2,
        flashalpha         = 0.2,
        flashsize          = 1000,
        ttl                = 48,
        color = {
          [1]  = 0.3,
          [2]  = 0,
          [3]  = 0.4,
        },
      },
      sphere = {
        air                = true,
        class              = [[CSpherePartSpawner]],
        count              = 1,
        ground             = true,
        water              = true,
        underwater         = true,
        properties = {
          alpha              = 0.6,
          color              = [[0.3,0,0.4]],
          expansionspeed     = 13.2,
          ttl                = 40,
        },
      },
      muzzleflash = {
        air                = true,
        class              = [[CSimpleParticleSystem]],
        count              = 1,
        ground             = true,
        water              = true,
        underwater         = true,
        properties = {
          colormap           = [[1 0.7 0.2 0.01    1 0.7 0.2 0.01    0 0 0 0.01]],
          directional        = true,
          emitrot            = 0,
          emitrotspread      = 0,
          emitvector         = [[dir]],
          gravity            = [[0, 0, 0]],
          numparticles       = 1,
          particlelife       = 90,
          particlelifespread = 0,
          particlesize       = 0,
          particlespeed      = 0,
          particlespeedspread = 0,
          pos                = [[0, 0, 0]],
          sizegrowth         = 0,
          sizemod            = 0,
          texture            = [[plasma]],
        },
      },
    },
}