VFS.Include("LuaRules/Utilities/to_make_op_things.lua")
local utils=Spring.Utilities.to_make_op_things

return utils.copy_tweak_silly_build_morth("staticcon","staticcontanky","sillycon",utils.table_replace({
    name                          = [[Tanky Caretaker]],
    description                   = [[Tanky Construction Assistant]],
    health=1750,
    metalCost=250,
    explodeAs                     = [[NOWEAPON]],
    selfDestructAs=[[NOWEAPON]],
    buildoptions={
        [[staticradar]],
        [[staticheavyradar]],
        [[staticshield]],
        [[staticjammer]],
        [[turretmissile]],
        [[turretlaser]],
        [[turretimpulse]],
        [[turretemp]],
        [[turretriot]],
        [[turretheavylaser]],
        [[turretgauss]],
        [[turretantiheavy]],
        [[turretheavy]],
        [[turrettorp]],
        [[turretaalaser]],
        [[turretaaclose]],
        [[turretaafar]],
        [[turretaaflak]],
        [[turretaaheavy]],
        [[staticantinuke]],
        [[staticarty]],
        [[staticheavyarty]],
        [[staticmissilesilo]],
        [[staticcontanky]],
        [[energypylon]],
        [[staticmex]],
        [[energysolar]],
        [[energyfusion]],
    },
}))